//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Script/Player/PlayerInput/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""3cdbc0b0-5f29-48e1-86db-260def44818d"",
            ""actions"": [
                {
                    ""name"": ""LClick"",
                    ""type"": ""Button"",
                    ""id"": ""7f316b82-c2bb-4c27-9a62-20c8b527dc6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RClick"",
                    ""type"": ""Button"",
                    ""id"": ""b77f600a-54a2-47be-8f7f-ebecad28b1d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""73ff0142-119e-4278-b166-7f2b86e7ffeb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill_Q"",
                    ""type"": ""Button"",
                    ""id"": ""1182b3e1-08ca-410a-bc66-5efebe8155f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill_W"",
                    ""type"": ""Button"",
                    ""id"": ""738789e6-1f08-4908-a3dd-537296e899bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill_E"",
                    ""type"": ""Button"",
                    ""id"": ""eae70bf6-3765-44a8-9e8c-8b730ec88621"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill_R"",
                    ""type"": ""Button"",
                    ""id"": ""ad602e9d-faa9-4915-9182-47a0573808cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill_A"",
                    ""type"": ""Button"",
                    ""id"": ""f4f38fd1-420e-49a4-bcfd-d3f78467d8a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill_S"",
                    ""type"": ""Button"",
                    ""id"": ""88ebee95-5ea6-4574-8215-932b116169dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill_D"",
                    ""type"": ""Button"",
                    ""id"": ""2bf5c789-0921-4076-945f-58e8a183423f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill_F"",
                    ""type"": ""Button"",
                    ""id"": ""cb395e62-a52d-4fc4-b099-2164c43f363f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""021af2cc-82bf-4532-87fd-29f7f23f359f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e715d00-86c0-4a56-a5c8-c32051513663"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill_Q"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29fb8875-b8ea-4b49-a7b7-0b72beb3cbaa"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd4d59f8-0732-421c-9a3f-15e91c7e6922"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill_W"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2572926-a6f5-4a01-b5df-be726f2e2136"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill_E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ff438be-3db0-476b-9700-6fa3a879c8c7"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill_R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3e8c75e-0d02-403b-bade-863a9cdb0bf1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill_A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b87e62f-baaf-4fbb-81c2-4eccf77d400f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill_S"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e679d078-2820-4ace-adff-5b0cc3fce512"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill_D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f7b4df0-d0d9-4e0e-8d9b-25f3d8f9e052"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill_F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b629457c-4126-46d5-84c5-3e7a257bb16b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_LClick = m_Player.FindAction("LClick", throwIfNotFound: true);
        m_Player_RClick = m_Player.FindAction("RClick", throwIfNotFound: true);
        m_Player_Space = m_Player.FindAction("Space", throwIfNotFound: true);
        m_Player_Skill_Q = m_Player.FindAction("Skill_Q", throwIfNotFound: true);
        m_Player_Skill_W = m_Player.FindAction("Skill_W", throwIfNotFound: true);
        m_Player_Skill_E = m_Player.FindAction("Skill_E", throwIfNotFound: true);
        m_Player_Skill_R = m_Player.FindAction("Skill_R", throwIfNotFound: true);
        m_Player_Skill_A = m_Player.FindAction("Skill_A", throwIfNotFound: true);
        m_Player_Skill_S = m_Player.FindAction("Skill_S", throwIfNotFound: true);
        m_Player_Skill_D = m_Player.FindAction("Skill_D", throwIfNotFound: true);
        m_Player_Skill_F = m_Player.FindAction("Skill_F", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_LClick;
    private readonly InputAction m_Player_RClick;
    private readonly InputAction m_Player_Space;
    private readonly InputAction m_Player_Skill_Q;
    private readonly InputAction m_Player_Skill_W;
    private readonly InputAction m_Player_Skill_E;
    private readonly InputAction m_Player_Skill_R;
    private readonly InputAction m_Player_Skill_A;
    private readonly InputAction m_Player_Skill_S;
    private readonly InputAction m_Player_Skill_D;
    private readonly InputAction m_Player_Skill_F;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LClick => m_Wrapper.m_Player_LClick;
        public InputAction @RClick => m_Wrapper.m_Player_RClick;
        public InputAction @Space => m_Wrapper.m_Player_Space;
        public InputAction @Skill_Q => m_Wrapper.m_Player_Skill_Q;
        public InputAction @Skill_W => m_Wrapper.m_Player_Skill_W;
        public InputAction @Skill_E => m_Wrapper.m_Player_Skill_E;
        public InputAction @Skill_R => m_Wrapper.m_Player_Skill_R;
        public InputAction @Skill_A => m_Wrapper.m_Player_Skill_A;
        public InputAction @Skill_S => m_Wrapper.m_Player_Skill_S;
        public InputAction @Skill_D => m_Wrapper.m_Player_Skill_D;
        public InputAction @Skill_F => m_Wrapper.m_Player_Skill_F;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @LClick.started += instance.OnLClick;
            @LClick.performed += instance.OnLClick;
            @LClick.canceled += instance.OnLClick;
            @RClick.started += instance.OnRClick;
            @RClick.performed += instance.OnRClick;
            @RClick.canceled += instance.OnRClick;
            @Space.started += instance.OnSpace;
            @Space.performed += instance.OnSpace;
            @Space.canceled += instance.OnSpace;
            @Skill_Q.started += instance.OnSkill_Q;
            @Skill_Q.performed += instance.OnSkill_Q;
            @Skill_Q.canceled += instance.OnSkill_Q;
            @Skill_W.started += instance.OnSkill_W;
            @Skill_W.performed += instance.OnSkill_W;
            @Skill_W.canceled += instance.OnSkill_W;
            @Skill_E.started += instance.OnSkill_E;
            @Skill_E.performed += instance.OnSkill_E;
            @Skill_E.canceled += instance.OnSkill_E;
            @Skill_R.started += instance.OnSkill_R;
            @Skill_R.performed += instance.OnSkill_R;
            @Skill_R.canceled += instance.OnSkill_R;
            @Skill_A.started += instance.OnSkill_A;
            @Skill_A.performed += instance.OnSkill_A;
            @Skill_A.canceled += instance.OnSkill_A;
            @Skill_S.started += instance.OnSkill_S;
            @Skill_S.performed += instance.OnSkill_S;
            @Skill_S.canceled += instance.OnSkill_S;
            @Skill_D.started += instance.OnSkill_D;
            @Skill_D.performed += instance.OnSkill_D;
            @Skill_D.canceled += instance.OnSkill_D;
            @Skill_F.started += instance.OnSkill_F;
            @Skill_F.performed += instance.OnSkill_F;
            @Skill_F.canceled += instance.OnSkill_F;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @LClick.started -= instance.OnLClick;
            @LClick.performed -= instance.OnLClick;
            @LClick.canceled -= instance.OnLClick;
            @RClick.started -= instance.OnRClick;
            @RClick.performed -= instance.OnRClick;
            @RClick.canceled -= instance.OnRClick;
            @Space.started -= instance.OnSpace;
            @Space.performed -= instance.OnSpace;
            @Space.canceled -= instance.OnSpace;
            @Skill_Q.started -= instance.OnSkill_Q;
            @Skill_Q.performed -= instance.OnSkill_Q;
            @Skill_Q.canceled -= instance.OnSkill_Q;
            @Skill_W.started -= instance.OnSkill_W;
            @Skill_W.performed -= instance.OnSkill_W;
            @Skill_W.canceled -= instance.OnSkill_W;
            @Skill_E.started -= instance.OnSkill_E;
            @Skill_E.performed -= instance.OnSkill_E;
            @Skill_E.canceled -= instance.OnSkill_E;
            @Skill_R.started -= instance.OnSkill_R;
            @Skill_R.performed -= instance.OnSkill_R;
            @Skill_R.canceled -= instance.OnSkill_R;
            @Skill_A.started -= instance.OnSkill_A;
            @Skill_A.performed -= instance.OnSkill_A;
            @Skill_A.canceled -= instance.OnSkill_A;
            @Skill_S.started -= instance.OnSkill_S;
            @Skill_S.performed -= instance.OnSkill_S;
            @Skill_S.canceled -= instance.OnSkill_S;
            @Skill_D.started -= instance.OnSkill_D;
            @Skill_D.performed -= instance.OnSkill_D;
            @Skill_D.canceled -= instance.OnSkill_D;
            @Skill_F.started -= instance.OnSkill_F;
            @Skill_F.performed -= instance.OnSkill_F;
            @Skill_F.canceled -= instance.OnSkill_F;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnLClick(InputAction.CallbackContext context);
        void OnRClick(InputAction.CallbackContext context);
        void OnSpace(InputAction.CallbackContext context);
        void OnSkill_Q(InputAction.CallbackContext context);
        void OnSkill_W(InputAction.CallbackContext context);
        void OnSkill_E(InputAction.CallbackContext context);
        void OnSkill_R(InputAction.CallbackContext context);
        void OnSkill_A(InputAction.CallbackContext context);
        void OnSkill_S(InputAction.CallbackContext context);
        void OnSkill_D(InputAction.CallbackContext context);
        void OnSkill_F(InputAction.CallbackContext context);
    }
}
